### PR TITLE
Delete booking and created house on the frontend

### PR DESCRIPTION
**Pull request by Charptr0**
# Changes
+ Added controller for removing created houses and bookings in gateway
+ Added a way to verify refresh and access tokens before answering the requests
+ Added button when pressed will send a request to delete a specific house listing
+ Added button when pressed will send a request to delete a specific created booking

### CODE REVIEW

**Comment by deepankarck2** [comment]
I have reviewed the changes you have made to delete bookings and houses on the frontend, and I think they look good.  The addition of a way to verify refresh and access tokens before answering the requests is also a good security measure. It will help to prevent unauthorized access to the system and protect our server and the user's data.

**Comment by sritarung** [comment]
The changes of bookings and houses on frontend look good to me.

**Comment by Muhammad-Rahman922** [comment]
I have reviewed the changes made and can confirm it indeed works.

**Comment by Haseebzz** [comment]
I have reviewed your changes and everything looks good. The controller for removing houses and bookings in the gateway work as well as the added functionality to verify refresh and access tokens before answering requests. The buttons are another great feature that allows the deletion of specific houses and creating of bookings. Overall, looks good, and keep up the great work!

**Comment by Haseebzz** [comment]
! I have reviewed your changes and everything looks good. I appreciate the addition of the controller for removing houses and bookings in the gateway, and the added functionality to verify refresh and access tokens before answering requests. Also, the buttons to delete specific house listings and created bookings are a great addition. Keep up the good work!"

**Comment by mahfuz6543** [comment]
Was able to delete the houses using the buttons and to create booking. The changes work and looks good

**Comment by Muhammad-Rahman922** [comment]
Since I'm having issues registering and logging in, I'll have to take your words for it that all is well.

**Pull request merged**
