### PR TITLE
New dashboard with userhouse page.

### PR DESCRIPTION
**Pull request by Haseebzz**
These are some of the changes that I've made
App.jsx
I created a new route that leads to Userhouse
AllHouseList.jsx
Added some styling and cleaned up some of the JSON data. Note that I will probably include more or maybe perhaps create
an individual page displaying the information of the place once a user clicks on one.
Header.jsx
Added functionality if a user has a token meaning they are logged in so if they click the profile icon it will take them to the dashboard and if not logged in it will lead them to the login page. Also, I made the username display where the profile icon is making it easier.
Dashboard.jsx
updated and styled the dashboard by creating a button that leads to the Userhouse path. Also, I made it so that when a user logout it will refresh the page because if it doesn't the username still shows on the icon.
AddHouse.jsx and Home.jsx
added some basic styling using Tailwind
Userhouse.jsx
a new page that fetches the places of the user that is signed in.

### CODE REVIEW

**Review by Charptr0 — COMMENTED** [review]
Awesome, I like the new styles.

The only issue I have seen was that in the page /add-house, the **submit button** was missing from the page. 

If you can added the submit button to the bottom again that will be great. 

Also, next time when you create your branch, can you use a better naming scheme to describe your branch instead of `new`. Thanks 👍

**Comment by Haseebzz** [comment]
> Awesome, I like the new styles.
> 
> The only issue I have seen was that in the page /add-house, the **submit button** was missing from the page.
> 
> If you can added the submit button to the bottom again that will be great.
> 
> Also, next time when you create your branch, can you use a better naming scheme to describe your branch instead of `new`. Thanks 👍

Sounds good, but the submit button was there it was just next to the price so I moved it down instead.

**Review by Charptr0 — APPROVED** [review]
LTGM 👍

**Comment by deepankarck2** [comment]
Great job on these changes! I reviewed your pull request and I'm impressed with the improvements you've made to the codebase.

I appreciate the addition of the new route to Userhouse in App.jsx, and the cleanup and styling changes in AllHouseList.jsx. It's good to see that you're planning to add even more functionality to display the information of the place once a user clicks on one.

**Comment by Muhammad-Rahman922** [comment]
I like the changes made and it looks good to me.

**Comment by sritarung** [comment]
Looks good

**Pull request merged**
