### PR TITLE
updated ui for header and made logo navigate to homepage

### PR DESCRIPTION
**Pull request by Haseebzz**
We didn't have a link that would take us back to the home page so I made the logo a link that would take us back to the homepage.

### CODE REVIEW

**Comment by Charptr0** [comment]
I like the new logo, it look a lot better than what we have before 👍 

But, it **DOES NOT** goes to the homepage (/), it goes to the browse page (/browse). Is that intentional?

**Review by Charptr0 — COMMENTED** [review]
I like the new logo, it look a lot better than what we have before 👍

But, it DOES NOT goes to the homepage (/), it goes to the browse page (/browse). Is that intentional?

**Review by Charptr0 — APPROVED** [review]
LGTM! Now it is pointing to the home page.

**Comment by sritarung** [comment]
Issue fixed. It works properly. It goes to the home page now.

**Comment by deepankarck2** [comment]
**Issue:** 
The code changes not working as intended. The hyperlink does not go to the homepage of our website. But it goes to the browse page (/browse). 

**Updated Comment:**
I tested it on my end. The embedded link on the logo seems to be working properly. It is a really great add-on for the UX or user experience of our app.

**Pull request merged**
