### PR TITLE
added booking unit test

### PR DESCRIPTION
**Pull request by Charptr0**
# Changes
+ Added 5 unit tests to test the features related to booking

# Unit tests
1. Get the added house's id
2. Add a new booking to that house
3. Make sure that the booking has been added to the database
4. Remove the booking
5. Make sure that the booking has been removed

### CODE REVIEW

**Review by deepankarck2 — COMMENTED** [review]
I have reviewed and run the code on my end. The tests cover a range of functionalities, including getting the added house's id, adding a new booking to that house, making sure that the booking has been added to the database, removing the booking, and making sure that the booking has been removed.  They will be added along with a CI pipeline to ensure continuous testing and integration. 

**Feedback:** My only feedback is that it takes a few minutes for the tests to be able to run. If I try to run the tests immediately after creating the containers, the tests fail. It takes a about 5-6 minutes after a container starts running for the tests to be able to pass. Not sure if it's an API run time issue, or an internal docker issue.

**Comment by sritarung** [comment]
It works for all the mentioned unit tests as intended. It works for the insertion, fetch, booking and deletion routes of house service. I approve this merge request.

**Comment by Haseebzz** [comment]
I ran the unit tests and they have all successfully pass. ran them locally and they all passed successfully.  Overall, looks good to me.

**Comment by Haseebzz** [comment]
I ran the unit tests and they have all worked. Overall, looks good to me.

**Comment by mahfuz6543** [comment]
All the unit tests worked successfully that has been implemented. Was able to insert/delete house to the database.

**Pull request merged**
