### PR TITLE
Auth UI test

### PR DESCRIPTION
**Pull request by deepankarck2**
## Description:
This pull request introduces two new UI tests for the Register and Login routes of our application. The tests are implemented using Python and Selenium, with the web driver-manager package to manage WebDrivers in different machines.

## Changes made:

- Added index.py for running both register, and login tests at once 
- Added register_ui_test.py for testing the Register route.
- Added login_ui_test.py for testing the Login route.

## Instructions for running the tests:
* Install the required packages using pip:
* Copy code
` pip install selenium webdriver-manager ` 
* Run `docker compose up` 
*  Remove frontend container 
*  Run `npm start ` on the forntend folder
* Navigate to the `frontend/test` directory.
### Run both tests using following: 
` python index.py` 

Run Individually: 
* Run the Register UI test by executing the following command:
Copy code
`python register_ui_test.py`
* Run the Login UI test by executing the following command:
Copy code
`python login_ui_test.py`

Please review the added test scripts and let me know if any changes are required. Once the tests are approved, we can integrate them into our continuous integration pipeline to ensure the smooth functioning of the Register and Login routes.

### CODE REVIEW

**Review by Charptr0 — COMMENTED** [review]
I got this error after following the above instructions

```
test_register_form (register_ui_test.RegisterUITest) ...
DevTools listening on ws://127.0.0.1:58208/devtools/browser/7c6d7f3c-4d85-4c6c-934f-17da523e1ad7
ERROR
test_login_form (login_ui_test.LoginUITest) ...
DevTools listening on ws://127.0.0.1:58229/devtools/browser/b9662b25-aa37-4d13-aa17-9f5d97ed1297
ERROR

======================================================================
ERROR: test_register_form (register_ui_test.RegisterUITest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\Charl\Desktop\Courses\CSC 456\booking-app\frontend\test\register_ui_test.py", line 18, in test_register_form
    username_input = driver.find_element_by_id("reg-username")
AttributeError: 'WebDriver' object has no attribute 'find_element_by_id'

======================================================================
ERROR: test_login_form (login_ui_test.LoginUITest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\Charl\Desktop\Courses\CSC 456\booking-app\frontend\test\login_ui_test.py", line 18, in test_login_form
    email_input = driver.find_element_by_id("login-email")
AttributeError: 'WebDriver' object has no attribute 'find_element_by_id'

----------------------------------------------------------------------
Ran 2 tests in 7.864s
```

**Comment by Haseebzz** [comment]
I'm also getting errors when I run python index.py. It gives me this
```ERROR: test_register_form (register_ui_test.RegisterUITest.test_register_form)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Haseeb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haseeb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\Haseeb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\http\client.py", line 1375, in getresponse
    response.begin()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Haseeb\456 final\Booking-app\frontend\test\register_ui_test.py", line 13, in setUp
    self.driver.get("http://localhost:3000/register")
  File "C:\Users\Haseeb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\selenium\webdriver\remote\webdriver.py", line 449, in get
    self.execute(Command.GET, {"url": url})
  File "C:\Users\Haseeb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\selenium\webdriver\remote\webdriver.py", line 438, in execute
    response = self.command_executor.execute(driver_command, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haseeb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\selenium\webdriver\remote\remote_connection.py", line 290, in execute
    return self._request(command_info[0], url, body=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haseeb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\selenium\webdriver\remote\remote_connection.py", line 311, in _request
    response = self._conn.request(method, url, body=body, headers=headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haseeb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\urllib3\request.py", line 78, in request        
    return self.request_encode_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haseeb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\urllib3\request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haseeb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\urllib3\poolmanager.py", line 376, in urlopen   
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haseeb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haseeb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\urllib3\util\retry.py", line 550, in increment  
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haseeb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\urllib3\packages\six.py", line 769, in reraise  
    raise value.with_traceback(tb)
  File "C:\Users\Haseeb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haseeb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\Haseeb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\http\client.py", line 1375, in getresponse
    response.begin()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
fra8p0\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\socket.py", line 706, in readinto      
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
======================================================================
ERROR: test_login_form (login_ui_test.LoginUITest.test_login_form)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Haseeb\456 final\Booking-app\frontend\test\login_ui_test.py", line 18, in test_login_form
    email_input = driver.find_element_by_id("login-email")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'WebDriver' object has no attribute 'find_element_by_id'

----------------------------------------------------------------------
Ran 2 tests in 15.477s

FAILED (errors=2)```

**Comment by deepankarck2** [comment]
> ```
> AttributeError: 'WebDriver' object has no attribute 'find_element_by_id'
> ```
I have refactored the code to account for the error. The selenium seems like removed that specific method. Please try again.

**Review by Charptr0 — APPROVED** [review]
Good stuff 👍 

Both tests are working and I got an `OK` debug message back.

Currently there is no way to remove the test user from the database in which it will cause the register test to fail if the test was to run again. It is not a huge issue since there is no way to delete the account on the frontend anyways. Other than that, no issues

**Review by sritarung — APPROVED** [review]
This looks good. Both tests are working

**Comment by mahfuz6543** [comment]
The tests are working fine now. Good work

**Comment by Muhammad-Rahman922** [comment]
Unfortunately, the above tests don't pass for me. it stems from being unable to login, if it works for all of you though, then I'll have to take your words for it.

**Pull request merged**
