### PR TITLE
created footer ui with github link attached

### PR DESCRIPTION
**Pull request by Haseebzz**
@mahfuz6543  and I made a footer that displays the GitHub link and appears in every page.

### CODE REVIEW

**Comment by sritarung** [comment]
Yes. There seems to be a glitch or an issue with the user interface as it seems to be logging me off after repeated clicking on browse. The name on account also disappears and appears with the issue.

**Comment by deepankarck2** [comment]
There is an issue with the code. I have pasted the errors below. Is the error reproducible? Please let me know if there is an issue on my end. 

` Compiled with problems:
ERROR in ./src/Footer.jsx 5:0-42
Module not found: Error: Can't resolve 'react-icons/fa' in 'A:\CCNY\I_Spring_2023\CSC456\Project\Booking-app\frontend\src'`

`ERROR in ./src/Footer.jsx 6:0-40
Module not found: Error: Can't resolve 'react-icons/si' in 'A:\CCNY\I_Spring_2023\CSC456\Project\Booking-app\frontend\src' `

**Comment by Charptr0** [comment]
> There is an issue with the code. I have pasted the errors below. Is the error reproducible? Please let me know if there is an issue on my end.
> 
> ` Compiled with problems: ERROR in ./src/Footer.jsx 5:0-42 Module not found: Error: Can't resolve 'react-icons/fa' in 'A:\CCNY\I_Spring_2023\CSC456\Project\Booking-app\frontend\src'`
> 
> `ERROR in ./src/Footer.jsx 6:0-40 Module not found: Error: Can't resolve 'react-icons/si' in 'A:\CCNY\I_Spring_2023\CSC456\Project\Booking-app\frontend\src' `

The error name speaks for it self, `MODULE_NOT_FOUND` you need to update the frontend to have the latest dependencies. Trying running `inp.sh` file.

**Comment by sritarung** [comment]
npm install react-icons fixed the issue for me. The footer looks good.

**Comment by mahfuz6543** [comment]
The footer will be fixed soon, right now it always on displays

**Comment by Muhammad-Rahman922** [comment]
The footer seems to have been fixed.

**Pull request merged**
