### PR TITLE
House service and User contexts

### PR DESCRIPTION
**Pull request by Charptr0**
# Contributions

## Backend
+ Added a new house service that will handle all requests relating to booking and housing
+ If the current service is running in development mode, it will generate 10 sample dummy houses provided by chatgpt
+ Added routes to insert, delete and fetch a house document with its 

## Frontend
+ User (owners) can create a house by visiting the /add-house URL
+ Added user context to keep track of the user's username, id, and email throughout the app
+ Guest and registered users can now view all the houses that are in the database by visiting /browse
+ Owner of houses can view their listings on their dashboards

### CODE REVIEW

**Comment by Haseebzz** [comment]
I have reviewed the following code and can confirm that these features work successfully. For the backend, the house service for handling requests related to booking and housing has been added to the backend. Also, the backend routes for insert, delete and fetch work correctly by using thunder client to test the endpoints. Also, the front-end users can create their own houses, view houses in the MongoDB database, and can view their own listings on their dashboards if they are the owner of the house. React context has been successfully implemented as well to keep track of the user information throughout our app.
I have tested these changes on my local environment and have confirmed that they have worked.

**Comment by deepankarck2** [comment]
After reviewing the code on this pull request and testing the features, I can approve the integration of this branch with the master branch. I have done some quick end-to-end testing by simulating user interactions with the application. I verified that users, can create a house by visiting the /add-house URL, and that the house document is inserted and stored correctly in the database. I also conducted **edge-case testing** to account for any possible scenarios that may arise during real-world usage. This included testing for error handling, edge cases with invalid inputs, and ensuring proper handling of exceptions.

**Comment by sritarung** [comment]
There is an issue with the login and registering system. Even though the database is running, there seems to be a 500 status error with registering and logging in.  It is letting me log in sometimes and sometimes it does not. Other than that, there is no other issue. When logged in, I tested that the users can create their own houses, view houses  listings on their dashboards if they are the owner of the house.

**Comment by Charptr0** [comment]
> There is an issue with the login and registering system. Even though the database is running, there seems to be a 500 status error with registering and logging in. It is letting me log in sometimes and sometimes it does not. Other than that, there is no other issue. When logged in, I tested that the users can create their own houses, view houses listings on their dashboards if they are the owner of the house.

Try running the script I wrote `inp.sh` to update all your dependencies. This was the issue for @Haseebzz. If you continue to encounter issues, please dm me 👍

**Comment by mahfuz6543** [comment]
After reviewing and testing the new features I also verify that registered users can add houses to the database with adding the descriptions. Backend now includes the house service, which is responsible for handling booking and housing requests. And I don't see any issue with either logging in or while registering with running the script.

**Comment by Muhammad-Rahman922** [comment]
I reviewed the code and the features mentioned work successfully. Regarding the front end, users can now create a house listing. Owners are able to see all their listings as well. Users and guests are also now able to see all the houses in the database.  Regarding the backend, a housing service has been added that handles all booking and housing requests.  Registering and logging in were working as intended as well.

**Pull request merged**
