### PR TITLE
Added House unit test

### PR DESCRIPTION
**Pull request by Charptr0**
# Changes
Added 7 unit test for the House service that test the features of adding, fetching, and remove a house from the database.

# Running the test
1. Run `inp,sh` file to download the latest dependencies
2. Run the backend by doing `docker compose up`
3. Open the docker and go to the `containers` section
4. Go to the container named `house-service-container`
5. Click the console icon
6. Run the command `npm run test`

### CODE REVIEW

**Comment by deepankarck2** [comment]
All tests are running well within the house-service-container. I will integrate the tests into the CI pipeline as the next step.

**Review by deepankarck2 — COMMENTED** [review]
All tests are running well within the house-service-container. I will integrate the tests into the CI pipeline as the next step.

**Comment by Haseebzz** [comment]
Looking good to me. All tests are running well.

**Comment by Muhammad-Rahman922** [comment]
All tests are passing for me as well.

**Pull request merged**
