### PR TITLE
Event calendar

### PR DESCRIPTION
**Pull request by Charptr0**
# Changes
+ When placing a booking, the user is able to choose the dates
+ Shows a confirmation message and reload the page when removing booking and house
+ Minimal bug fixes

### CODE REVIEW

**Comment by deepankarck2** [comment]
Event calendar for choosing dates looks good. Implementing a confirmation message and page reload when removing a booking and house is a nice UX addon, ensuring that users receive clear feedback when performing these actions and reducing any potential confusion.

**Comment by mahfuz6543** [comment]
The implementation was really user friendly, the host already shows the available dates and the event calendar pops up while choosing the dates. And it shows corresponding confirmation messages based on the users choosing.

**Comment by sritarung** [comment]
This makes it very user friendly to choose dates and in getting feedback for removing booking and house. Good job.

**Comment by Haseebzz** [comment]
The even calender is a great addition when booking a place. Looks very good.

**Comment by Muhammad-Rahman922** [comment]
I agree this is a great QOL user friendly improvement

**Pull request merged**
