### PR TITLE
added bookings functionalities to the backend and frontend

### PR DESCRIPTION
**Pull request by Charptr0**
# Changes
+ Added the ability to create a bookings a specific house on the browse page (user not able to choose the dates)
+ Moved dashboard functionalities to act more as components (routing to another page removed)
+ Added a critically needed back button to go back to the dashboard
+ Added the backend functionalities to be able to add, fetch, and delete bookings from the database
+ Refactored jsx files to keep the work spaces organized
+ Formatting fixes

### CODE REVIEW

**Review by deepankarck2 — COMMENTED** [review]
I have thoroughly reviewed the changes you have made and I am happy to approve this pull request. Your additions will allow users to create bookings for specific houses on the browse page, and the newly added back button will provide a much-needed convenience for users to navigate through the website. The refactored JSX files and formatting fixes show a strong attention to detail and organization.

**Comment by sritarung** [comment]
It looks good to me. The booking for specific houses and other features work as intended

**Comment by mahfuz6543** [comment]
The added back button surely helps the user to go dashboard easily. Your new implementation also make the user able to create booking for houses.

**Comment by Haseebzz** [comment]
I like the changes! I liked how you implemented the ability to create bookings for a specific house on the browse page as well as the back button. The dashboard functionalities help improves the user experience and refactoring the jsx files is important because it keeps it organized. Overall, these changes look good to me.

**Pull request merged**
