### PR TITLE
removed un-used features that is causing the app to crash

### PR DESCRIPTION
**Pull request by Charptr0**
emergency fix to make sure the frontend is able to compile

### CODE REVIEW

**Comment by Haseebzz** [comment]
these changes look good to me. It seems that this small bug has been fixed.

**Comment by deepankarck2** [comment]
Thanks for the immediate initiative. It was indeed causing errors. Looks good now.

**Comment by sritarung** [comment]
looks good now

**Comment by mahfuz6543** [comment]
There seems to be no more error

**Comment by Muhammad-Rahman922** [comment]
The fix seems to have worked, there isn't an error anymore.

**Pull request merged**
