### PR TITLE
add deposit to back and frontend

### PR DESCRIPTION
**Pull request by Charptr0**
# Changes
+ Backend:  Added the functionality to add and fetch the deposited amount of a specific user
+ Frontend: User are now be able to access the deposit screen via the dashboard
+ Frontend: User are now able to deposit money into their account

### CODE REVIEW

**Comment by deepankarck2** [comment]
I've reviewed the changes made to both the backend and frontend of the application and everything looks good to me. I was able to deposit money and then see my balance after refreshing.  

However, I did notice that the input box for depositing money is hard to see. To improve the user experience, could you please add a border to the input box to make it more noticeable?

**Comment by Charptr0** [comment]
> However, I did notice that the input box for depositing money is hard to see. To improve the user experience, could you please add a border to the input box to make it more noticeable?

I think @Haseebzz is in charge of the styles, I will let him know 👍

**Comment by sritarung** [comment]
It looks good to me

**Comment by mahfuz6543** [comment]
Yes all the following frontend features successfully worked. Looks good

**Comment by Haseebzz** [comment]
I have tested the deposit feature and it works. I loved the feature.

**Comment by Muhammad-Rahman922** [comment]
I can confirm that it works as intended

**Pull request merged**
