### PR TITLE
Create digital-ocean-deploy.yml

### PR DESCRIPTION
**Pull request by deepankarck2**
[Feature] Deploying App with Digital Ocean

Description:
Created a new GitHub Actions workflow `digital-ocean-deploy.yml` that triggers deployment of our app on Digital Ocean, a cloud computing platform, whenever someone pushes/merges changes to the master branch. The workflow creates a `.env` file with environment variables for our app, runs `docker-compose up -d` to start the containers, and deploys the app in a development environment.

Changes:
- Added `digital-ocean-deploy.yml` workflow file
- Configured workflow to trigger on pushes/merges to master branch
- Created `.env` file with environment variables for the app
- Started Docker containers with `docker-compose up -d`

Team Members:
Please review the changes and provide feedback. This workflow will help automate our deployment process and ensure that our app is always up-to-date on Digital Ocean. Thank you!

### CODE REVIEW

**Review by Charptr0 — APPROVED** [review]
LGTM!

**Comment by Muhammad-Rahman922** [comment]
I confirm it loads as intended. Looks good.

**Comment by Haseebzz** [comment]
I have reviewed the changes for the addition of the digital-ocean-deploy.yml  and approved this pull request. Overall, looks good and is a good improvement for our project.

**Comment by sritarung** [comment]
I have checked the deployment at my end. It seems to work as intended for continuous deployment( deploys whenever someone pushes something to main).
I approve this pull request.

**Pull request merged**
