### PR TITLE
Add House UI Test

### PR DESCRIPTION
**Pull request by deepankarck2**
# Add Automated Testing for AddHouse Feature

## Description:

This pull request adds automated testing for the AddHouse feature. It includes the following changes:

* Added `credentials.py` file: This file contains the credentials for a test user which are used for logging in during the test run.

* Created `addHouse_ui_test.py` file: This file contains a Selenium test case for the AddHouse feature. It first logs in using the credentials from credentials.py, then navigates to the AddHouse page and fills in the form with test data. It then submits the form and checks that the user is redirected to the dashboard, indicating a successful form submission.

* Added `addHouse_ui_test` to `index.py` : The AddHouse test case is now included in the main test runner, index.py. This means it will be run along with the other tests when index.py is run.

## Instructions for running the tests:
* Run `docker compose up` 
*  Remove frontend container 
*  Run `npm start ` on the frontend folder
* Navigate to the `frontend/test` directory.
### Run all three tests using the following: 
` python index.py` 

## Result:
**All 3 tests should pass.**

image

#### Note if your tests are causing issues, try changing the credentials in the credentials.py file

### CODE REVIEW

**Comment by Haseebzz** [comment]
looks good to me

**Comment by sritarung** [comment]
This works as intended running 3 tests.

**Comment by Charptr0** [comment]
It worked on my end, good work 👍

**Comment by mahfuz6543** [comment]
All the tests also worked for me.

**Comment by Muhammad-Rahman922** [comment]
looks good to me

**Pull request merged**
